### ISSUE TITLE
Virtual procedures

### ISSUE THREAD

**Issue by netbsduser** [roecrew/nymph#1]
Are there plans for Nymph to support virtual procedures?

**Comment by maelswarm** [comment]
@JX7P 
hmmm, it would be nice to override.
I think that would be awesome!

Do you have anything specific in mind?

**Comment by KTRosenberg** [comment]
Would the idea be to reinvent C with classes (early C++)?

By the way, I find this project neat. Would it be okay if I were to propose some minor changes/add some error checking while I look through the code (in a fork)?

**Comment by maelswarm** [comment]
@KTRosenberg 
Go for it!
