### ISSUE TITLE
Where to go next?

### ISSUE THREAD

**Issue by maelswarm** [roecrew/nymph#11]
Aside from virtual procedures, are there any features you guys would like?

**Comment by reverofevil** [comment]
Type inference.

**Comment by r-lyeh** [comment]
- Reflection
- Default function arguments
- Lambdas

**Comment by thesw4rm** [comment]
Creating generator functions, similar to those you'd make in Python with the yield statement.

**Comment by maelswarm** [comment]
Thanks for the interest @ytpillai !
Is this something you'd be willing to help implement?

**Comment by thesw4rm** [comment]
Sure, but I'm not very experienced in C. I'll try to help however I can.

**Comment by maelswarm** [comment]
@ytpillai 
I'm going to start a new issue for this topic.
Let's talk there?
