### ISSUE TITLE
garbage collection

### ISSUE THREAD

**Issue by dodona2** [roecrew/nymph#14]
first of all cool project!
Is a garbage collection scheduled?

**Comment by roecrew** [comment]
Right now we are just "chaining" all mallocs. A minimal and efficient GC would be awesome!

**Comment by dodona2** [comment]
why not: http://www.hboehm.info/gc/

**Comment by isaachier** [comment]
If you make the language garbage collected, those interested in the raw C compatibility may be driven away (myself included).
