### ISSUE TITLE
Self-referential structs.

### ISSUE THREAD

**Issue by websnarf** [roecrew/nymph#16]
To do a typical self-referentially defined structure in C you typically have to do the following:

    struct node; /* This is necessary ... */
    struct node {
        char msg[128];
        struct node* next; /* ... so that the compiler knows what this is */
    };

So the question is, why not make it so that in Nymph all named structs are scanned for and then just declared in bare format at the top of the preprocessed C file, so that you can omit this seemingly unnecessary redundant empty code from the user.

**Comment by maelswarm** [comment]
@websnarf 
This is technically already implemented.

What I want to be able to do is this.
````c
struct node {
    char msg[128];
    struct node next; /* ... so that the compiler knows what this is */
};
````
