### ISSUE TITLE
Make does not work

### ISSUE THREAD

**Issue by halosm1th** [roecrew/nymph#4]
Using the make file that you provided, it does not work. After fixing square to rect it worked but now fails because there is no method named create or print. 
Output from running make:
`gcc -std=c11 nymph_compiler.c -o nymph
./nymph rect.n rect
public
public
./nymph box.n box
public
public
./nymph main.n main
gcc -std=c11 -c rect.c rect.h
gcc -std=c11 -c box.c box.h
gcc -std=c11 -c main.c main.h
main.c: In function ‘main’:
main.c:9:1: warning: implicit declaration of function ‘create’ [-Wimplicit-function-declaration]
 create(&myBox);
 ^
main.c:14:1: warning: implicit declaration of function ‘print’ [-Wimplicit-function-declaration]
 print(myBox);
 ^
gcc -std=c11 main.o box.o rect.o -o out
main.o: In function `main':
main.c:(.text+0x2b): undefined reference to `create'
main.c:(.text+0x3c): undefined reference to `create'
main.c:(.text+0x4d): undefined reference to `print'
main.c:(.text+0x5e): undefined reference to `print'
collect2: error: ld returned 1 exit status
makefile:2: recipe for target 'nymph' failed
make: *** [nymph] Error 1
`

**Comment by maelswarm** [comment]
@halosm1th 
Sorry about that. Right now Nymph is a work in progress.

Update: Just saw your pull request. Thank you for the edit!
