### ISSUE TITLE
char *postPrepareFunction(char *statement) can read past start of statement array

### ISSUE THREAD

**Issue by rwhitworth** [roecrew/nymph#8]
Around line 1106 of `nymph_pp.c` there is a chance to read out of bounds.  The character before the start of the statement pointer can be read.

I found this error with the provided box.n sample files.

1106-1108
```
char *postPrepareFunction(char *statement) {
    char *tmp = strstr(statement, "(") - 1;
    for (; isalnum(tmp[0]) != 0; tmp--) {}
```

I think those same lines of code could be changed to:
```
	char *tmp = strstr(statement, "(") - 1;
	while (statement - tmp >= 0 && isalnum(tmp[0]) != 0)
		tmp--;
```

**Comment by maelswarm** [comment]
@rwhitworth 
Please submit a pull request when you have a chance.
